# Generated by Django 4.1.3 on 2022-11-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.expressions.Case, related_name='watchlist_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
