# Generated by Django 4.1.3 on 2022-11-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.CharField(default='None', max_length=1),
        ),
    ]
