# Generated by Django 4.1.3 on 2022-11-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_list_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
